const express = require("express");
const router = express.Router();
const stripeService = require("../services/stripeService");
const db = require("../db");
const stripe = stripeService.stripe;

// This physically intercepts raw Buffer bytes, which is explicitly why we bypass express.json() for this exact route!
router.post("/", async (req, res) => {
  const sig = req.headers['stripe-signature'];
  const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET || 'whsec_dummy_local_secret';

  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, endpointSecret);
  } catch (err) {
    console.error(`Stripe Webhook Cryptographic Verification Failed: ${err.message}`);
    // If the crypto hash generated by Stripe doesn't perfectly match our environment secret, reject heavily!
    return res.status(400).send(`Webhook Security Validation Error: ${err.message}`);
  }

  // Handle the highly authorized event payloads
  switch (event.type) {
    case 'checkout.session.completed': {
      const session = event.data.object;
      const widgetId = session.client_reference_id || session.metadata?.widget_id;
      const customerId = session.customer;
      const subscriptionId = session.subscription;

      // Extract the exact Plan they ultimately paid for
      if (!widgetId) break;

      // We actively resolve their physical Node database parameters 
      const planSql = `SELECT plan_code FROM saas_plans WHERE stripe_price_id = ? LIMIT 1`;
      
      // Pull the price ID heavily nested in the session map
      stripe.subscriptions.retrieve(subscriptionId).then(subObj => {
          const priceId = subObj.items.data[0].price.id;
          
          db.query(planSql, [priceId], (err, results) => {
             if (err || !results.length) return;
             const assignedPlan = results[0].plan_code;

             // Map the secure mathematical update forcing the user into 'active' ecosystem mode!
             const upsertSql = `
                INSERT INTO subscriptions (widget_id, plan_code, stripe_customer_id, stripe_subscription_id, status, current_period_end)
                VALUES (?, ?, ?, ?, ?, FROM_UNIXTIME(?))
                ON DUPLICATE KEY UPDATE 
                   plan_code = ?, stripe_customer_id = ?, stripe_subscription_id = ?, status = ?, current_period_end = FROM_UNIXTIME(?)
             `;
             
             const safePeriodEnd = subObj.current_period_end; // Unix timestamp
             const values = [widgetId, assignedPlan, customerId, subscriptionId, 'active', safePeriodEnd, assignedPlan, customerId, subscriptionId, 'active', safePeriodEnd];
             
             db.query(upsertSql, values, () => {
                console.log(`[Stripe Ecosystem] Account ${widgetId} securely unlocked onto Plan Matrix: ${assignedPlan}`);
             });
          });
      });
      break;
    }
    case 'customer.subscription.updated': {
      const subscriptionData = event.data.object;
      const status = subscriptionData.status; // 'active', 'past_due', 'canceled', 'unpaid'
      const cancelAtPeriodEnd = subscriptionData.cancel_at_period_end;
      const subIdRef = subscriptionData.id;
      const periodEnd = subscriptionData.current_period_end;

      const updateSql = `
         UPDATE subscriptions 
         SET status = ?, cancel_at_period_end = ?, current_period_end = FROM_UNIXTIME(?)
         WHERE stripe_subscription_id = ?
      `;
      db.query(updateSql, [status, cancelAtPeriodEnd, periodEnd, subIdRef]);
      
      // If Stripe structurally declared the user 'past_due' (like CC declined), the Widget API naturally rejects their logic
      break;
    }
    case 'customer.subscription.deleted': {
      const deletedSub = event.data.object;
      
      db.query(`UPDATE subscriptions SET status = 'canceled' WHERE stripe_subscription_id = ?`, [deletedSub.id]);
      break;
    }
    default:
      console.log(`Unhandled Stripe Webhook hook logic: ${event.type}`);
  }

  // Mandatory 200 HTTP response signaling Stripe they can stop re-sending the ping!
  res.status(200).send();
});

module.exports = router;
